model:
  model_name: DefaultModel
  attention_pre_norm_affine: true
  classifier_pre_norm_affine: true
  feed_forward_pre_norm_affine: true
  norm_eps: 1.e-7
  d_h: 64
  hidden_size: 192
  num_attention_heads: 3
  intermediate_size: 768
  num_layers: 6
  vocab_size: 51200
  max_sequence_length: 512
  rope_theta: 10000
  tie_weights: false
  dataset_type: causal
  compile_model: false

data:
  train_path: data/train_tokens
  valid_path: data/valid_tokens
  num_shards: 1
  num_train_tokens: 1.e+8
  dataset_type: causal
  max_sequence_length: 512
  mask_p_max: 0.3
  mask_p_min: 0.1
  mask_random_p: 0.1
  mask_keep_p: 0.1
  tokenizer_path: tokenizers/tokenizer.json
  n_special_tokens: 16

training:
  seed: 42
  load_checkpoint: false
  checkpoint_path:
  hybrid_numerator: 1
  hybrid_denominator: 1
  z_loss_weight: 0.0001
  max_steps: 1000
  number_of_tokens: 
  local_batch_size: 16
  global_batch_size: 64
  adam_learning_rate: 1.e-4
  muon_learning_rate: 1.e-2
  scheduler: cosine
  warmup_proportion: 0.1
  cooldown_proportion: 0.1
  adam_weight_decay: 0.0
  muon_weight_decay: 0.1
  max_gradient: 1.0
  optimizer: normuon
  adam_eps: 1.e-8
  adam_beta1: 0.9
  adam_beta2: 0.95
  momentum: 0.95
  muon_beta2: 0.95

checkpointing:
  output_dir: checkpoints
  save_every: 1000
  checkpoint_style: linear
  first_checkpoint: 1000
  checkpoint_every: 1000
  checkpoint_mult: 1.0
  checkpoint_on: steps
  checkpoint_init: false
  checkpoint_before_cooldown: false

logging:
  run_name: "default_run"
  experiment: "default"
  wandb_log: false
  wandb_project:
  wandb_entity:
  validate_every: 100
  validation_steps: 1

distributed:
  distributed: false
